### ISSUE TITLE
Maximum update depth exceeded, crashing the dashboard

### ISSUE THREAD

**Issue by tarjelavik** [robinpyon/sanity-plugin-dashboard-widget-vercel#1]
Hi! I tried to the plugin now in a v2.3.6 studio, but the dashboard crashes after clicking deploy. The deployment starts and is running after reloading the studio.

Have you experienced this? Feels like i have misconfigured something?...

Stack trace:

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (/static/js/vendor.bundle.js:25883:15)
    at scheduleUpdateOnFiber (/static/js/vendor.bundle.js:23954:3)
    at Object.enqueueSetState (/static/js/vendor.bundle.js:15429:5)
    at SnackbarProvider.1904.Component.setState (/static/js/vendor.bundle.js:1335:16)
    at Object.updateSnack (/static/js/app.bundle.js:839728:14)
    at DefaultSnackbar.componentDidUpdate (/static/js/app.bundle.js:60303:18)
    at DefaultSnackbar.componentDidUpdate (/static/js/app.bundle.js:847050:123)
    at commitLifeCycles (/static/js/vendor.bundle.js:22625:22)
    at commitLayoutEffects (/static/js/vendor.bundle.js:25593:7)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:2978:14)
```

Component stack:

```
in DefaultSnackbar (created by DeployButton)
    in DeployButton (created by Widget)
    in div (created by Widget)
    in div (created by Context.Consumer)
    in Styled(div) (created by Widget)
    in MDXProvider (created by MDXProvider$1)
    in MDXProvider$1 (created by ThemeProvider$1)
    in ColorModeProvider (created by ThemeProvider$1)
    in BaseProvider (created by ThemeProvider)
    in ThemeProvider (created by ThemeProvider$1)
    in ThemeProvider$1 (created by Widget)
    in ReactQueryCacheProvider (created by Widget)
    in Widget (created by WidgetContainer)
    in div (created by WidgetContainer)
    in WidgetContainer (created by WidgetGroup)
    in div (created by WidgetGroup)
    in WidgetGroup (created by Dashboard)
    in div (created by DashboardLayout)
    in div (created by DashboardLayout)
    in DashboardLayout (created by Dashboard)
    in Dashboard (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by AppProvider)
    in div (created by styled.div)
    in styled.div (created by Box)
    in Box (created by Styled(Box))
    in Styled(Box) (created by Card)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by Card)
    in Card (created by Styled(Card))
    in Styled(Card) (created by AppProvider)
    in SnackbarProvider (created by AppProvider)
    in ToastProvider (created by AppProvider)
    in LayerProvider (created by AppProvider)
    in PortalProvider (created by AppProvider)
    in UserColorManagerProvider (created by AppProvider)
    in AppProvider (created by SanityRoot)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer
```

**Comment by robinpyon** [comment]
Thanks for reporting @tarjelavik! 

Does the issue still persist after trying the following?
- remove your `node_modules` folder 
- remove `package-lock.json`/ `yarn.lock` 
- re-run `npm install` / `yarn install`

If that doesn't work for you, please paste the output of `sanity versions` and `npm -v && node -v`– thanks!

**Comment by tarjelavik** [comment]
Ah! Great, it worked after deleting `node_modules`. Should have tried that before bothering you, sry!
